name: Build-Publish
on:
  push:
    branches: [main, dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        -
          name: Set up Dockercompose Build
          uses: docker/setup-buildx-action@v1
          run: docker-compose build

          #name: Set up Docker Buildx
          #uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          run: docker-compose push
          #with:
          #  context: ./web_server
          #  file: ./web_server/Dockerfile
          #  push: true
          #  tags: ${{ secrets.DOCKER_USERNAME }}/webserver_test:latest
            