name: publish
on:
  push:
    branches: [main, dev]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: login github container registry
      run: |
        echo $PAT | docker login ghcr.io -u cdozen --password-stdin
      env:
        PAT: ${{ secrets.PAT }}

    - name: Build the hello-world Docker image
      run: |
        cd web_server
        docker build . --tag ghcr.io/cdozen/hello-world:latest
        docker run ghcr.io/cdozen/hello-world:latest
        docker push ghcr.io/cdozen/hello-world:latest
